const Countries  = [ 
    {countryName: "Afghanistan", code: "AF"}, 
    {countryName: "land Islands", code: "AX"}, 
    {countryName: "Albania", code: "AL"}, 
    {countryName: "Algeria", code: "DZ"}, 
    {countryName: "American Samoa", code: "AS"}, 
    {countryName: "AndorrA", code: "AD"}, 
    {countryName: "Angola", code: "AO"}, 
    {countryName: "Anguilla", code: "AI"}, 
    {countryName: "Antarctica", code: "AQ"}, 
    {countryName: "Antigua and Barbuda", code: "AG"}, 
    {countryName: "Argentina", code: "AR"}, 
    {countryName: "Armenia", code: "AM"}, 
    {countryName: "Aruba", code: "AW"}, 
    {countryName: "Australia", code: "AU"}, 
    {countryName: "Austria", code: "AT"}, 
    {countryName: "Azerbaijan", code: "AZ"}, 
    {countryName: "Bahamas", code: "BS"}, 
    {countryName: "Bahrain", code: "BH"}, 
    {countryName: "Bangladesh", code: "BD"}, 
    {countryName: "Barbados", code: "BB"}, 
    {countryName: "Belarus", code: "BY"}, 
    {countryName: "Belgium", code: "BE"}, 
    {countryName: "Belize", code: "BZ"}, 
    {countryName: "Benin", code: "BJ"}, 
    {countryName: "Bermuda", code: "BM"}, 
    {countryName: "Bhutan", code: "BT"}, 
    {countryName: "Bolivia", code: "BO"}, 
    {countryName: "Bosnia and Herzegovina", code: "BA"}, 
    {countryName: "Botswana", code: "BW"}, 
    {countryName: "Bouvet Island", code: "BV"}, 
    {countryName: "Brazil", code: "BR"}, 
    {countryName: "British Indian Ocean Territory", code: "IO"}, 
    {countryName: "Brunei Darussalam", code: "BN"}, 
    {countryName: "Bulgaria", code: "BG"}, 
    {countryName: "Burkina Faso", code: "BF"}, 
    {countryName: "Burundi", code: "BI"}, 
    {countryName: "Cambodia", code: "KH"}, 
    {countryName: "Cameroon", code: "CM"}, 
    {countryName: "Canada", code: "CA"}, 
    {countryName: "Cape Verde", code: "CV"}, 
    {countryName: "Cayman Islands", code: "KY"}, 
    {countryName: "Central African Republic", code: "CF"}, 
    {countryName: "Chad", code: "TD"}, 
    {countryName: "Chile", code: "CL"}, 
    {countryName: "China", code: "CN"}, 
    {countryName: "Christmas Island", code: "CX"}, 
    {countryName: "Cocos (Keeling) Islands", code: "CC"}, 
    {countryName: "Colombia", code: "CO"}, 
    {countryName: "Comoros", code: "KM"}, 
    {countryName: "Congo", code: "CG"}, 
    {countryName: "Congo, The Democratic Republic of the", code: "CD"}, 
    {countryName: "Cook Islands", code: "CK"}, 
    {countryName: "Costa Rica", code: "CR"}, 
    {countryName: "Cote D'Ivoire", code: "CI"}, 
    {countryName: "Croatia", code: "HR"}, 
    {countryName: "Cuba", code: "CU"}, 
    {countryName: "Cyprus", code: "CY"}, 
    {countryName: "Czech Republic", code: "CZ"}, 
    {countryName: "Denmark", code: "DK"}, 
    {countryName: "Djibouti", code: "DJ"}, 
    {countryName: "Dominica", code: "DM"}, 
    {countryName: "Dominican Republic", code: "DO"}, 
    {countryName: "Ecuador", code: "EC"}, 
    {countryName: "Egypt", code: "EG"}, 
    {countryName: "El Salvador", code: "SV"}, 
    {countryName: "Equatorial Guinea", code: "GQ"}, 
    {countryName: "Eritrea", code: "ER"}, 
    {countryName: "Estonia", code: "EE"}, 
    {countryName: "Ethiopia", code: "ET"}, 
    {countryName: "Falkland Islands (Malvinas)", code: "FK"}, 
    {countryName: "Faroe Islands", code: "FO"}, 
    {countryName: "Fiji", code: "FJ"}, 
    {countryName: "Finland", code: "FI"}, 
    {countryName: "France", code: "FR"}, 
    {countryName: "French Guiana", code: "GF"}, 
    {countryName: "French Polynesia", code: "PF"}, 
    {countryName: "French Southern Territories", code: "TF"}, 
    {countryName: "Gabon", code: "GA"}, 
    {countryName: "Gambia", code: "GM"}, 
    {countryName: "Georgia", code: "GE"}, 
    {countryName: "Germany", code: "DE"}, 
    {countryName: "Ghana", code: "GH"}, 
    {countryName: "Gibraltar", code: "GI"}, 
    {countryName: "Greece", code: "GR"}, 
    {countryName: "Greenland", code: "GL"}, 
    {countryName: "Grenada", code: "GD"}, 
    {countryName: "Guadeloupe", code: "GP"}, 
    {countryName: "Guam", code: "GU"}, 
    {countryName: "Guatemala", code: "GT"}, 
    {countryName: "Guernsey", code: "GG"}, 
    {countryName: "Guinea", code: "GN"}, 
    {countryName: "Guinea-Bissau", code: "GW"}, 
    {countryName: "Guyana", code: "GY"}, 
    {countryName: "Haiti", code: "HT"}, 
    {countryName: "Heard Island and Mcdonald Islands", code: "HM"}, 
    {countryName: "Holy See (Vatican City State)", code: "VA"}, 
    {countryName: "Honduras", code: "HN"}, 
    {countryName: "Hong Kong", code: "HK"}, 
    {countryName: "Hungary", code: "HU"}, 
    {countryName: "Iceland", code: "IS"}, 
    {countryName: "India", code: "IN"}, 
    {countryName: "Indonesia", code: "ID"}, 
    {countryName: "Iran, Islamic Republic Of", code: "IR"}, 
    {countryName: "Iraq", code: "IQ"}, 
    {countryName: "Ireland", code: "IE"}, 
    {countryName: "Isle of Man", code: "IM"}, 
    {countryName: "Israel", code: "IL"}, 
    {countryName: "Italy", code: "IT"}, 
    {countryName: "Jamaica", code: "JM"}, 
    {countryName: "Japan", code: "JP"}, 
    {countryName: "Jersey", code: "JE"}, 
    {countryName: "Jordan", code: "JO"}, 
    {countryName: "Kazakhstan", code: "KZ"}, 
    {countryName: "Kenya", code: "KE"}, 
    {countryName: "Kiribati", code: "KI"}, 
    {countryName: "Korea, Democratic People 'S Republic of", code: "KP"}, 
    {countryName: "Korea, Republic of", code: "KR"}, 
    {countryName: "Kuwait", code: "KW"}, 
    {countryName: "Kyrgyzstan", code: "KG"}, 
    {countryName: "Lao People 'S Democratic Republic", code: "LA"}, 
    {countryName: "Latvia", code: "LV"}, 
    {countryName: "Lebanon", code: "LB"}, 
    {countryName: "Lesotho", code: "LS"}, 
    {countryName: "Liberia", code: "LR"}, 
    {countryName: "Libyan Arab Jamahiriya", code: "LY"}, 
    {countryName: "Liechtenstein", code: "LI"}, 
    {countryName: "Lithuania", code: "LT"}, 
    {countryName: "Luxembourg", code: "LU"}, 
    {countryName: "Macao", code: "MO"}, 
    {countryName: "Macedonia, The Former Yugoslav Republic of", code: "MK"}, 
    {countryName: "Madagascar", code: "MG"}, 
    {countryName: "Malawi", code: "MW"}, 
    {countryName: "Malaysia", code: "MY"}, 
    {countryName: "Maldives", code: "MV"}, 
    {countryName: "Mali", code: "ML"}, 
    {countryName: "Malta", code: "MT"}, 
    {countryName: "Marshall Islands", code: "MH"}, 
    {countryName: "Martinique", code: "MQ"}, 
    {countryName: "Mauritania", code: "MR"}, 
    {countryName: "Mauritius", code: "MU"}, 
    {countryName: "Mayotte", code: "YT"}, 
    {countryName: "Mexico", code: "MX"}, 
    {countryName: "Micronesia, Federated States of", code: "FM"}, 
    {countryName: "Moldova, Republic of", code: "MD"}, 
    {countryName: "Monaco", code: "MC"}, 
    {countryName: "Mongolia", code: "MN"}, 
    {countryName: "Montenegro", code: "ME"},
    {countryName: "Montserrat", code: "MS"},
    {countryName: "Morocco", code: "MA"}, 
    {countryName: "Mozambique", code: "MZ"}, 
    {countryName: "Myanmar", code: "MM"}, 
    {countryName: "Namibia", code: "NA"}, 
    {countryName: "Nauru", code: "NR"}, 
    {countryName: "Nepal", code: "NP"}, 
    {countryName: "Netherlands", code: "NL"}, 
    {countryName: "Netherlands Antilles", code: "AN"}, 
    {countryName: "New Caledonia", code: "NC"}, 
    {countryName: "New Zealand", code: "NZ"}, 
    {countryName: "Nicaragua", code: "NI"}, 
    {countryName: "Niger", code: "NE"}, 
    {countryName: "Nigeria", code: "NG"}, 
    {countryName: "Niue", code: "NU"}, 
    {countryName: "Norfolk Island", code: "NF"}, 
    {countryName: "Northern Mariana Islands", code: "MP"}, 
    {countryName: "Norway", code: "NO"}, 
    {countryName: "Oman", code: "OM"}, 
    {countryName: "Pakistan", code: "PK"}, 
    {countryName: "Palau", code: "PW"}, 
    {countryName: "Palestinian Territory, Occupied", code: "PS"}, 
    {countryName: "Panama", code: "PA"}, 
    {countryName: "Papua New Guinea", code: "PG"}, 
    {countryName: "Paraguay", code: "PY"}, 
    {countryName: "Peru", code: "PE"}, 
    {countryName: "Philippines", code: "PH"}, 
    {countryName: "Pitcairn", code: "PN"}, 
    {countryName: "Poland", code: "PL"}, 
    {countryName: "Portugal", code: "PT"}, 
    {countryName: "Puerto Rico", code: "PR"}, 
    {countryName: "Qatar", code: "QA"}, 
    {countryName: "Reunion", code: "RE"}, 
    {countryName: "Romania", code: "RO"}, 
    {countryName: "Russian Federation", code: "RU"}, 
    {countryName: "RWANDA", code: "RW"}, 
    {countryName: "Saint Helena", code: "SH"}, 
    {countryName: "Saint Kitts and Nevis", code: "KN"}, 
    {countryName: "Saint Lucia", code: "LC"}, 
    {countryName: "Saint Pierre and Miquelon", code: "PM"}, 
    {countryName: "Saint Vincent and the Grenadines", code: "VC"}, 
    {countryName: "Samoa", code: "WS"}, 
    {countryName: "San Marino", code: "SM"}, 
    {countryName: "Sao Tome and Principe", code: "ST"}, 
    {countryName: "Saudi Arabia", code: "SA"}, 
    {countryName: "Senegal", code: "SN"}, 
    {countryName: "Serbia", code: "RS"}, 
    {countryName: "Seychelles", code: "SC"}, 
    {countryName: "Sierra Leone", code: "SL"}, 
    {countryName: "Singapore", code: "SG"}, 
    {countryName: "Slovakia", code: "SK"}, 
    {countryName: "Slovenia", code: "SI"}, 
    {countryName: "Solomon Islands", code: "SB"}, 
    {countryName: "Somalia", code: "SO"}, 
    {countryName: "South Africa", code: "ZA"}, 
    {countryName: "South Georgia and the South Sandwich Islands", code: "GS"}, 
    {countryName: "Spain", code: "ES"}, 
    {countryName: "Sri Lanka", code: "LK"}, 
    {countryName: "Sudan", code: "SD"}, 
    {countryName: "Suriname", code: "SR"}, 
    {countryName: "Svalbard and Jan Mayen", code: "SJ"}, 
    {countryName: "Swaziland", code: "SZ"}, 
    {countryName: "Sweden", code: "SE"}, 
    {countryName: "Switzerland", code: "CH"}, 
    {countryName: "Syrian Arab Republic", code: "SY"}, 
    {countryName: "Taiwan, Province of China", code: "TW"}, 
    {countryName: "Tajikistan", code: "TJ"}, 
    {countryName: "Tanzania, United Republic of", code: "TZ"}, 
    {countryName: "Thailand", code: "TH"}, 
    {countryName: "Timor-Leste", code: "TL"}, 
    {countryName: "Togo", code: "TG"}, 
    {countryName: "Tokelau", code: "TK"}, 
    {countryName: "Tonga", code: "TO"}, 
    {countryName: "Trinidad and Tobago", code: "TT"}, 
    {countryName: "Tunisia", code: "TN"}, 
    {countryName: "Turkey", code: "TR"}, 
    {countryName: "Turkmenistan", code: "TM"}, 
    {countryName: "Turks and Caicos Islands", code: "TC"}, 
    {countryName: "Tuvalu", code: "TV"}, 
    {countryName: "Uganda", code: "UG"}, 
    {countryName: "Ukraine", code: "UA"}, 
    {countryName: "United Arab Emirates", code: "AE"}, 
    {countryName: "United Kingdom", code: "GB"}, 
    {countryName: "United States", code: "US"}, 
    {countryName: "United States Minor Outlying Islands", code: "UM"}, 
    {countryName: "Uruguay", code: "UY"}, 
    {countryName: "Uzbekistan", code: "UZ"}, 
    {countryName: "Vanuatu", code: "VU"}, 
    {countryName: "Venezuela", code: "VE"}, 
    {countryName: "Viet Nam", code: "VN"}, 
    {countryName: "Virgin Islands, British", code: "VG"}, 
    {countryName: "Virgin Islands, U.S.", code: "VI"}, 
    {countryName: "Wallis and Futuna", code: "WF"}, 
    {countryName: "Western Sahara", code: "EH"}, 
    {countryName: "Yemen", code: "YE"}, 
    {countryName: "Zambia", code: "ZM"}, 
    {countryName: "Zimbabwe", code: "ZW"} 
    ]

module.exports = Countries;
